version: "3.9"

services:
  smartdine_backend:
    container_name: smartdine_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/Afi/Desktop/SmartDine/backend/project:/app"
    env_file:
      - .env       
    environment:
      - PYTHONUNBUFFERED=1
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

volumes:
  smartdine_db_data:
